# Generated by Django 4.1.7 on 2023-05-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whatsappapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversation',
            name='conversation_language',
            field=models.CharField(default='English', max_length=10),
        ),
    ]
