# Generated by Django 4.1.7 on 2023-06-02 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plantkb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='disease_diseased_bottom_leaf_image',
        ),
        migrations.RemoveField(
            model_name='disease',
            name='disease_diseased_top_leaf_image',
        ),
    ]
