# Generated by Django 4.1.7 on 2023-06-02 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageuploadform',
            name='name',
            field=models.CharField(default=4, max_length=100),
            preserve_default=False,
        ),
    ]
