# Generated by Django 4.1.7 on 2023-06-02 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapi', '0002_imageuploadform_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageuploadform',
            name='name',
        ),
    ]
