# Generated by Django 4.1.7 on 2023-05-16 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
        ('plantkb', '0001_initial'),
        ('experts', '0001_initial'),
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpertDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_diseased_top_leaf_image', models.ImageField(upload_to='detections')),
                ('detection_diseased_bottom_leaf_image', models.ImageField(upload_to='detections')),
                ('detection_latitude', models.CharField(max_length=30)),
                ('detection_longitude', models.CharField(max_length=30)),
                ('detection_temperature', models.IntegerField()),
                ('detection_humidity', models.IntegerField()),
                ('detection_wind_speed', models.IntegerField()),
                ('detection_rainfall', models.IntegerField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('detection_disease_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantkb.disease')),
                ('detection_expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experts.expert')),
                ('detection_farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmers.farmer')),
                ('detection_plant_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantkb.plant')),
                ('detection_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscription.usersubscription')),
                ('detection_treatments', models.ManyToManyField(to='plantkb.treatment')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
        migrations.CreateModel(
            name='AIModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detection_count', models.IntegerField(default=100000)),
                ('ai_model_version', models.FloatField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('detection_plant_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantkb.plant')),
            ],
            options={
                'ordering': ['-date_created'],
            },
        ),
    ]
